functionsDirectory = "/home/runner/workspace/netlify/functions"
functionsDirectoryOrigin = "default"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/home/runner/workspace/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/home/runner/workspace/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; connect-src 'self' https://api.airtable.com; style-src 'self' 'unsafe-inline';"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]