import { CHOICES } from './airtable.js';

// Form field specs per table, consumed by RecordModal.
// type: text | textarea | currency | number | percent | date | select | checkbox
export const FORMS = {
  BANKING_ACCOUNTS: [
    { name: 'Account Name', type: 'text', required: true },
    { name: 'Institution', type: 'text' },
    { name: 'Type', type: 'select', options: CHOICES.BANK_ACCOUNT_TYPE },
    { name: 'Owner', type: 'text', suggest: true },
    { name: 'Current Balance', type: 'currency' },
    { name: 'Previous Balance', type: 'currency' },
    { name: 'Target Amount', type: 'currency' },
    { name: 'Target Type', type: 'select', options: CHOICES.TARGET_TYPE },
    { name: 'Notes', type: 'textarea', full: true },
    { name: 'Active', type: 'checkbox', default: true },
    { name: 'Exclude from Net Worth', type: 'checkbox' },
  ],
  OWED_TO_ME: [
    { name: 'Person or Entity', type: 'text', required: true },
    { name: 'Type', type: 'select', options: CHOICES.OWED_TYPE },
    { name: 'Current Amount', type: 'currency' },
    { name: 'Previous Amount', type: 'currency' },
    { name: 'Notes', type: 'textarea', full: true },
  ],
  BANK_BONUSES: [
    { name: 'Bank Name', type: 'text', required: true },
    { name: 'Owner', type: 'text', suggest: true },
    { name: 'Business or Personal', type: 'select', options: CHOICES.BUSINESS_OR_PERSONAL },
    { name: 'Account Type', type: 'select', options: CHOICES.BONUS_ACCOUNT_TYPE },
    { name: 'Opened Date', type: 'date' },
    { name: 'Bonus Amount', type: 'currency' },
    { name: 'New Money Needed', type: 'currency' },
    { name: 'Direct Deposit Needed', type: 'currency' },
    { name: 'Date to Complete', type: 'date' },
    { name: 'Date Completed', type: 'date' },
    { name: 'Minimum Balance', type: 'text' },
    { name: 'Can Close Date', type: 'date' },
    { name: 'Closed Date', type: 'date' },
    { name: 'Notes', type: 'textarea', full: true },
  ],
  CREDIT_CARD_LOGINS: [
    { name: 'Login Label', type: 'text', required: true },
    { name: 'Issuer', type: 'select', options: CHOICES.ISSUER },
    { name: 'Owner', type: 'text', suggest: true },
    { name: 'Relationship', type: 'select', options: CHOICES.RELATIONSHIP },
    { name: 'Current Balance', type: 'currency' },
    { name: 'Previous Balance', type: 'currency' },
    { name: 'Notes', type: 'textarea', full: true },
  ],
  BALANCE_TRANSFERS: [
    { name: 'Card Name', type: 'text', required: true },
    { name: 'Status', type: 'select', options: CHOICES.TRANSFER_STATUS, default: 'Active' },
    { name: 'Amount Transferred', type: 'currency' },
    { name: 'Current Balance', type: 'currency' },
    { name: 'End Date', type: 'date' },
    { name: 'Notes', type: 'textarea', full: true },
  ],
  TRADING_PLATFORMS: [
    { name: 'Platform Name', type: 'text', required: true },
    { name: 'Owner', type: 'text', suggest: true },
    { name: 'Current Balance', type: 'currency' },
    { name: 'Previous Balance', type: 'currency' },
    { name: 'Notes', type: 'textarea', full: true },
  ],
  TRADING_LIQUIDATION: [
    { name: 'Label', type: 'text', default: 'Liquidation Invested' },
    { name: 'Current Balance', type: 'currency' },
    { name: 'Previous Balance', type: 'currency' },
    { name: 'Notes', type: 'textarea', full: true },
  ],
  SPECIAL_PROJECTS: [
    { name: 'Project Name', type: 'text', required: true },
    { name: 'Status', type: 'select', options: CHOICES.PROJECT_STATUS, default: 'Active' },
    { name: 'This Month Earned', type: 'currency' },
    { name: 'Last Month Earned', type: 'currency' },
    { name: 'This Month Spent', type: 'currency' },
    { name: 'Last Month Spent', type: 'currency' },
    { name: 'Available Balance', type: 'currency' },
    { name: 'Notes', type: 'textarea', full: true },
  ],
  PENDING_PAYOUTS: [
    { name: 'Source', type: 'text', required: true },
    { name: 'Amount', type: 'currency' },
    { name: 'Expected Date', type: 'date' },
    { name: 'Notes', type: 'textarea', full: true },
  ],
  INVESTMENTS: [
    { name: 'Account Name', type: 'text', required: true },
    { name: 'Owner', type: 'text', suggest: true },
    { name: 'Current Balance', type: 'currency' },
    { name: 'Previous Balance', type: 'currency' },
    { name: 'Notes', type: 'textarea', full: true },
    { name: 'Active', type: 'checkbox', default: true },
  ],
  SPORTSBOOKS: [
    { name: 'Book Name', type: 'text', required: true },
    { name: 'User', type: 'text', suggest: true },
    { name: 'Current Balance', type: 'currency' },
    { name: 'Previous Balance', type: 'currency' },
    { name: 'Notes', type: 'textarea', full: true },
    { name: 'Active', type: 'checkbox', default: true },
  ],
  SUBSCRIPTIONS: [
    { name: 'Name', type: 'text', required: true },
    { name: 'Amount', type: 'currency' },
    { name: 'Frequency', type: 'select', options: CHOICES.FREQUENCY, default: 'Monthly' },
    { name: 'Due Date', type: 'text', placeholder: 'e.g. 15th, Jan 1' },
    { name: 'Category', type: 'select', options: CHOICES.SUB_CATEGORY },
    { name: 'Owner', type: 'text', suggest: true },
    { name: 'Auto Pay', type: 'checkbox' },
    { name: 'Active', type: 'checkbox', default: true },
  ],
  MONTHLY_NET_WORTH: [
    { name: 'Month', type: 'text', required: true, placeholder: 'e.g. October 2026' },
    { name: 'Date', type: 'date' },
    { name: 'Total Banking', type: 'currency' },
    { name: 'Total Credit Card Debt', type: 'currency' },
    { name: 'Total Owed to Me', type: 'currency' },
    { name: 'Home Value', type: 'currency' },
    { name: 'Mortgage Balance', type: 'currency' },
    { name: 'Net Worth', type: 'currency', hint: 'Leave blank to auto-calculate' },
    { name: 'Change Percent', type: 'percent', hint: 'Leave blank to auto-calculate' },
    { name: 'Notes', type: 'textarea', full: true },
  ],
};
